"""Add Profile model and user password fields

Revision ID: 9ae087d03098
Revises: 
Create Date: 2025-10-26 22:39:13.278514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae087d03098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zelle_account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zelle_account_identifier', sa.String(length=120), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.drop_column('zelle_account_identifier')
        batch_op.drop_column('zelle_account_name')

    # ### end Alembic commands ###
