"""init: ...

Revision ID: f084de0bd212
Revises: 9ae087d03098
Create Date: 2025-10-27 18:46:31.050738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f084de0bd212'
down_revision = '9ae087d03098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.drop_column('payment_provider')
        batch_op.drop_column('zelle_account_name')
        batch_op.drop_column('zelle_account_identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zelle_account_identifier', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zelle_account_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_provider', postgresql.ENUM('CASHAPP', 'PAYPAL', 'VENMO', 'ZELLE', 'GENERIC', name='paymentprovider'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
